### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by VaibhavSys** [is-a-dev/docs#10]
The documentation is a bit outdated. There have been many new additions such as:

- ~~CLI~~ - #13
- Dashboard
- Hosting by is-a-dev
- ~~TXT Records Array~~ - da4e1da60c06c882766c7bec8185387420e57780
- ~~AAAA Records Support~~ - da4e1da60c06c882766c7bec8185387420e57780

**Comment by andrewstech** [comment]
Yup

**Comment by YouFoundAlpha** [comment]
> The documentation is a bit outdated. There have been many new additions such as:
> 
> - CLI
> - Dashboard
> - Hosting by is-a-dev
> - ~~TXT Records Array~~ - da4e1da60c06c882766c7bec8185387420e57780
> - ~~AAAA Records Support~~ - da4e1da60c06c882766c7bec8185387420e57780

I've added Cloudflare pages and Replit in the documentation 
https://github.com/is-a-dev/docs/pull/12
I can then try to add the CLI and Dashboard and Hosting by is-a.dev

**Comment by YouFoundAlpha** [comment]
> > The documentation is a bit outdated. There have been many new additions such as:
> > 
> > * CLI
> > * Dashboard
> > * Hosting by is-a-dev
> > * ~TXT Records Array~ - [da4e1da](https://github.com/is-a-dev/docs/commit/da4e1da60c06c882766c7bec8185387420e57780)
> > * ~AAAA Records Support~ - [da4e1da](https://github.com/is-a-dev/docs/commit/da4e1da60c06c882766c7bec8185387420e57780)
> 
> I've added Cloudflare pages and Replit in the documentation #12 I can then try to add the CLI and Dashboard and Hosting by is-a.dev

Just added a pull request for CLI

**Comment by YouFoundAlpha** [comment]
> > Just made a pull request for CLI [#13](https://github.com/is-a-dev/docs/pull/13)
> 
> Thank you! 😀

Will soon make one for hosting by is-a.dev

**Comment by YouFoundAlpha** [comment]
> > > Just made a pull request for CLI [#13](https://github.com/is-a-dev/docs/pull/13)
> > 
> > 
> > Thank you! 😀
> 
> Will soon make one for hosting by is-a.dev and Dashboard

Just made the PR for both #14

**Comment by YouFoundAlpha** [comment]
> > > Just made a pull request for CLI [#13](https://github.com/is-a-dev/docs/pull/13)
> > 
> > 
> > Thank you! 😀
> 
> Will soon make one for hosting by is-a.dev and Dashboard
The PR has been made @andrewstech @VaibhavSys
