### ISSUE TITLE
Clarify GitHub Pages deployment strategy

### ISSUE THREAD

**Issue by nullishamy** [is-a-dev/docs#11]
The [GitHub Pages deployment section](https://www.is-a.dev/docs/github_pages/) could do with some improvement. 

It does not provide instruction on how to get all GitHub Pages enabled repos that a user has onto the same `is-a.dev` root domain.
This *is* possible, but it does require certain (non-obvious) parts of the setup to be done in a particular way:

1) The website which hosts the "root" (`x.is-a.dev`) *must* be named `<username>.github.io`
2) That repo *must* have `x.is-a.dev` as the custom domain within the Pages settings.
3) Every other repo *must not* have a custom domain set in the Pages settings.
4) Links to other repos *must* end with `/` (e.g `https://amy.is-a.dev/args-ts/`)

I'd be more than happy to PR these points into this repo, but judging from the history I'm not sure if its a "team only" matter or if you accept public contributions.

**Comment by YouFoundAlpha** [comment]
@andrewstech Could you check this out?
